
spring:
  application:
    name: vic-ms-cliente-mq  # Identify this application
  freemarker:
    enabled: false     # Ignore Eureka dashboard FreeMarker templates


eureka:
  instance:
     leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

# HTTP Server
server:
  port: 2002   # HTTP (Tomcat) port